openapi: 3.0.0
info:
  title: savepost
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /savepost.php:
    post:
      summary: ''
      operationId: post-savepost.php
      responses:
        '200':
          description: OK
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                hptpr:
                  type: number
                hptbpr:
                  type: number
                dpdislk:
                  type: number
                dpdispr:
                  type: number
                hptlk:
                  type: number
                suara:
                  type: string
                  minLength: 1
                pil1:
                  type: number
                pil2:
                  type: number
                hpkpr:
                  type: number
                dpklk:
                  type: number
                hpklk:
                  type: number
                suararusak:
                  type: number
                hptblk:
                  type: number
                kodepet:
                  type: string
                  minLength: 1
                hpdispr:
                  type: number
                dptlk:
                  type: number
                dpkpr:
                  type: number
                dptbpr:
                  type: number
                tdksah:
                  type: number
                hpdislk:
                  type: number
                dptblk:
                  type: number
                dptpr:
                  type: number
              required:
                - hptpr
                - hptbpr
                - dpdislk
                - dpdispr
                - hptlk
                - suara
                - pil1
                - pil2
                - hpkpr
                - dpklk
                - hpklk
                - suararusak
                - hptblk
                - kodepet
                - hpdispr
                - dptlk
                - dpkpr
                - dptbpr
                - tdksah
                - hpdislk
                - dptblk
                - dptpr
            examples:
              example-1:
                value:
                  hptpr: 199
                  hptbpr: 6
                  dpdislk: 1
                  dpdispr: 2
                  hptlk: 1
                  suara: '[127,100]'
                  pil1: 127
                  pil2: 100
                  hpkpr: 4
                  dpklk: 1
                  hpklk: 3
                  suararusak: 0
                  hptblk: 9
                  kodepet: 0A0102000001001
                  hpdispr: 3
                  dptlk: 100
                  dpkpr: 0
                  dptbpr: 5
                  tdksah: 3
                  hpdislk: 5
                  dptblk: 17
                  dptpr: 101
          application/xml:
            schema:
              type: object
              properties: {}
          multipart/form-data:
            schema:
              type: object
              properties: {}
        description: ''
    put:
      summary: ''
      operationId: put-savepost.php
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
        description: ''
components:
  schemas: {}
